### ISSUE TITLE
fillValues case reflect.Int, reflect.Int64 provides error if header is not set

### ISSUE THREAD

**Issue by TorbenCK** [mozillazg/go-httpheader#4]
fillValues function returns error if header with int value is not set.

type ControllerPostParams struct {
	IntegerInJsonBody       int    `json:"integerInJsonBody" validate:"min=1,max=100000"`
	stringInHeader     string `header:"X-String,omitempty"`
}

The error occurs in switch case
case reflect.Int, reflect.Int64:
		var v int64
		if v, err = strconv.ParseInt(value, 10, 64); err != nil {
			return err
		}
		sv.SetInt(v)
		return nil

in case of an empty header value = "" strconv.ParseInt throws an error. I guess the same problem will occur in all number based switch cases from fillValues. I recommended to check if the header is set and otherwise exit the loop.

I know you can also set header:"-" in the struct tags, but this can be easily forgotten.
Additionally we initialise our params with defaults and httpheader.Decode overwrites everything if we do not set header:"-", which adds a lot of overhead in our stuct tags.

My proposal:
add an option that struct fields are left unharmed and are not overwritten with empty strings if no header is present.

**Comment by mozillazg** [comment]
@TorbenCK Thanks for reporting. I'll check it later.

**Comment by mozillazg** [comment]
Looks like that is a bug. I'll fix it soon.

>  I recommended to check if the header is set and otherwise exit the loop.

Yes, you're right. I'll fix it like this.

**Comment by mozillazg** [comment]
@TorbenCK I created a PR (#5) to fix this issue. Does it fix your problem?
